version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mti_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mti_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mti_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"  # Allow root connections from any host
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mti_network
    command: --default-authentication-plugin=mysql_native_password
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mti_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mti_network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  mti_network:
    driver: bridge